# Generated by Django 3.2.19 on 2023-05-18 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='../default_profile_uhncwe', upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_cuisine', models.CharField(choices=[('american', 'AMERICAN'), ('austrian', 'AUSTRIAN'), ('caribbean', 'CARIBBEAN'), ('chinese', 'CHINESE'), ('french', 'FRENCH'), ('german', 'GERMAN'), ('greek', 'GREEK'), ('indian', 'INDIAN'), ('italian', 'ITALIAN'), ('mediterranean', 'MEXICAN'), ('mexican', 'MEXICAN'), ('slovak', 'SLOVAK'), ('spanish', 'SPANISH')], default='american', max_length=13)),
                ('bio', models.CharField(default='', max_length=200)),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
