# Generated by Django 3.2.19 on 2024-01-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20231025_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favoriteCuisine',
            field=models.CharField(choices=[('american', 'AMERICAN'), ('austrian', 'AUSTRIAN'), ('caribbean', 'CARIBBEAN'), ('chinese', 'CHINESE'), ('french', 'FRENCH'), ('german', 'GERMAN'), ('greek', 'GREEK'), ('indian', 'INDIAN'), ('italian', 'ITALIAN'), ('mediterranean', 'Mediterranean'), ('mexican', 'MEXICAN'), ('slovak', 'SLOVAK'), ('spanish', 'SPANISH')], default='none', max_length=13),
        ),
    ]
