# Generated by Django 3.2.19 on 2024-01-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_favoritecuisine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favoriteCuisine',
            new_name='favorite_cuisine',
        ),
    ]
