# Generated by Django 3.2.19 on 2023-06-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_favorite_cuisine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-updated_at']},
        ),
    ]
