# Generated by Django 3.2.19 on 2023-10-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_inappropriate',
            field=models.BooleanField(default=False),
        ),
    ]
