# Generated by Django 3.2.19 on 2023-06-27 10:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_cuisine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='chef',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('owner', 'recipe')},
        ),
    ]
