CUISINE_CHOICES = (
    ('american', 'AMERICAN'),
    ('austrian', 'AUSTRIAN'),
    ('caribbean', 'CARIBBEAN'),
    ('chinese', 'CHINESE'),
    ('french', 'FRENCH'),
    ('german', 'GERMAN'),
    ('greek', 'GREEK'),
    ('indian', 'INDIAN'),
    ('italian', 'ITALIAN'),
    ('mediterranean', 'Mediterranean'),
    ('mexican', 'MEXICAN'),
    ('slovak', 'SLOVAK'),
    ('spanish', 'SPANISH'),
)