# Generated by Django 3.2.19 on 2023-05-22 19:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0002_auto_20230522_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='chef',
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('chef', 'followed')},
        ),
    ]
