# Generated by Django 3.2.19 on 2023-06-27 10:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0003_auto_20230522_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='chef',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('owner', 'followed')},
        ),
    ]
