# Generated by Django 3.2.19 on 2023-06-27 11:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0004_auto_20230627_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='owner',
            new_name='follower',
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('follower', 'followed')},
        ),
    ]
