# Generated by Django 3.2.19 on 2023-06-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_effort',
            field=models.TextField(default='', max_length=20),
        ),
    ]
