# Generated by Django 3.2.19 on 2023-05-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_effort',
            field=models.CharField(default='', max_length=20),
        ),
    ]
