# Generated by Django 3.2.19 on 2024-01-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_time_effort'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
