# Generated by Django 3.2.19 on 2024-01-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='../kitchen-ga12e7dca3_1920_ch64p1.jpg', upload_to='images/'),
        ),
    ]
