# Generated by Django 3.2.19 on 2023-05-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('american', 'AMERICAN'), ('austrian', 'AUSTRIAN'), ('caribbean', 'CARIBBEAN'), ('chinese', 'CHINESE'), ('french', 'FRENCH'), ('german', 'GERMAN'), ('greek', 'GREEK'), ('indian', 'INDIAN'), ('italian', 'ITALIAN'), ('mediterranean', 'MEXICAN'), ('mexican', 'MEXICAN'), ('slovak', 'SLOVAK'), ('spanish', 'SPANISH')], default='american', max_length=13),
        ),
    ]
