# Generated by Django 3.2.19 on 2024-03-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_effort',
            field=models.CharField(default='', max_length=20),
        ),
    ]
