# Generated by Django 3.2.19 on 2024-03-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_time_effort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='saved',
        ),
    ]
