# Generated by Django 3.2.19 on 2023-06-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_cuisine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='chef',
            new_name='owner',
        ),
    ]
